
spring:
  datasource:
    url: jdbc:mysql://rm-2ze93742pnkanoxpx4o.mysql.rds.aliyuncs.com:3306/etl?Unicode=true&useSSL=true&characterEncoding=UTF-8&?serverTimezone=GMT%2B8
    password: 5HQXBwy9J3igDf
    driver-class-name: com.mysql.jdbc.Driver
    username: etl

# Mybatis配置
mybatis:
  type-aliases-package: com.joywise.card.base.model
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true